name: Actions jobs to checkout
on:
  push:
jobs:
  Push_code_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Greeting message
        run: echo "Hello, GitHub!"
