name: Node JS Application
on:
  pull_request:
jobs:
  matrix_based_node_js_application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}  #this is goint to fetch the matrix.value dynamixally

      - name: Install dependencies
        run: npm install && echo " nom installung"
        

      - name: Run tests
        run: npm test
